### ISSUE TITLE
Make possibility to add random delay before each move

### ISSUE THREAD

**Issue by awdwad45456** [inushahapuarachchi/LichessBot#3]

**Comment by awdwad45456** [comment]
That also could prevent anticheat detection

**Comment by inushahapuarachchi** [comment]
Hi you can add this yourself. I don't want to modify master anymore.
Also in a previous version (check the history) it already did have delays and also made blunders on purpose to bypass the anti cheat.

I auto played a good couple hundred games before I ultra bullet with 0s moves and got flagged

https://lichess.org/@/ABotHasNoName

**Comment by inushahapuarachchi** [comment]
Use computer analysis (provided by lichess) on your own games to see the blunders and inaccuracies.
From what I recall seeing, they also flag you by IP address and fingerprinting.

Static delays are pretty blatant. I had some logic like if there was a big swing in score or losing/winning then take longer random delays otherwise smaller random delays.

Also I dynamically adjusted the bots difficulty. So every move it has a random 1/4 chance to use a very bad move (1/2 depth) otherwise like 3/4/5 depth.

Look through their repo to see what you need to bypass : https://github.com/ornicar/lila/blob/master/modules/evaluation/src/main/Assessible.scala﻿
